# Generated by Django 5.0.3 on 2025-02-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="iv",
            field=models.TextField(default=b"0"),
            preserve_default=False,
        ),
    ]
